// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = "1.9.23"
    repositories {
        jcenter()
        mavenCentral()
        google()
        maven { url 'https://jitpack.io' }
//        maven { url 'https://dl.bintray.com/umsdk/release' }
        maven { url 'https://maven.aliyun.com/repository/public/' }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.13.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        google()
        maven { url 'https://jitpack.io' }
//        maven { url 'https://dl.bintray.com/umsdk/release' }
        maven { url 'https://maven.aliyun.com/repository/public/' }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}


ext {
    compileSdkVersion = 30
    buildToolsVersion = "35.0.0"
    targetSdkVersion = 30
    ndkVersion = "21.0.6113669"

    versionName = '1.0'
    versionCode = 1

    xVersion = '1.1.0'
    blackReflection = '1.1.2'
}
